import React, { useEffect } from 'react';
import './AiMockInterview.css';
import QuestionAnswerIcon from '@mui/icons-material/QuestionAnswer';
import AssessmentIcon from '@mui/icons-material/Assessment';
import SupportAgentIcon from '@mui/icons-material/SupportAgent';
import Navbar from './Navbar';

const Aimockinterview = () => {
    useEffect(() => {
        window.scrollTo(0, 0);
      }, []);
  return (
   
    
    <div>
      <Navbar />
      <div className="aimockinterview-container">
        {/* Key Features Section */}
        <div className="grid-container">
          <div className="key-features">
            <h2>Key Features</h2>
            <div className="feature-item">
              <QuestionAnswerIcon fontSize="large" />
              <div>
                <h3>Realistic AI-Driven Questions</h3>
                <p>Experience interview questions generated by advanced AI, tailored to your industry and experience level.</p>
              </div>
            </div>
            <div className="feature-item">
              <AssessmentIcon fontSize="large" />
              <div>
                <h3>Comprehensive Performance Analysis</h3>
                <p>Receive detailed feedback on your answers, highlighting strengths and areas for improvement.</p>
              </div>
            </div>
            <div className="feature-item">
              <SupportAgentIcon fontSize="large" />
              <div>
                <h3>Post-Interview Guidance</h3>
                <p>Get advice from career experts to improve your interview skills and boost your confidence.</p>
              </div>
            </div>
          </div>

          {/* Subscription Section */}
          <div className="subscription-box">
            <h2>Choose Subscription</h2>
            <div className="subscription-options">
              <div className="subscription-option-box">
                <input type="radio" name="subscription" id="one-interview" />
                <label htmlFor="one-interview">1 Interview<br />₹1499*</label>
              </div>
              <div className="subscription-option-box">
                <input type="radio" name="subscription" id="three-interviews" />
                <label htmlFor="three-interviews">3 Interviews<br />₹3999</label>
              </div>
              <div className="subscription-option-box">
                <input type="radio" name="subscription" id="five-interviews" />
                <label htmlFor="five-interviews">5 Interviews<br />₹5999</label>
              </div>
            </div>
            <button className="buy-now">BUY NOW</button>

            {/* Discount Banner */}
            <div className="discount-banner">
              <p>Limited Time Offer - Get 20% off on all interview packages. Don’t miss out!</p>
            </div>
          </div>
        </div>

        {/* Benefits Section */}
        <div className="benefits-section">
          <h2>How our customers are succeeding?</h2>
          <div className="benefit-stats">
            <div className="stat-item">
              <div className="stat-circle">
                <p>2.3L</p>
                <span>Successfully completed interviews*</span>
              </div>
            </div>
            <div className="stat-item">
              <div className="stat-circle">
                <p>50.2%</p>
                <span>Improvement in interview performance*</span>
              </div>
            </div>
            <div className="stat-item">
              <div className="stat-circle">
                <p>27,889</p>
                <span>Users enhanced their skills with us</span>
              </div>
            </div>
          </div>
          <p className="note">*Data as of 1st Aug '24. Updated quarterly</p>
        </div>
      </div>
    </div>
  );
}

export default Aimockinterview;
